# Generated by Django 2.2.1 on 2019-05-12 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BicycleConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Breaks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GroupSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Manufactures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RepairShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RepairCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect', models.CharField(max_length=200)),
                ('price', models.IntegerField(null=True)),
                ('bicycleConfig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycleit.BicycleConfiguration')),
                ('repair_shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cycleit.RepairShop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycleit.User')),
            ],
        ),
        migrations.CreateModel(
            name='BicycleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycleit.Manufactures')),
            ],
        ),
        migrations.AddField(
            model_name='bicycleconfiguration',
            name='breaks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycleit.Breaks'),
        ),
        migrations.AddField(
            model_name='bicycleconfiguration',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycleit.Frame'),
        ),
        migrations.AddField(
            model_name='bicycleconfiguration',
            name='group_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycleit.GroupSet'),
        ),
        migrations.AddField(
            model_name='bicycleconfiguration',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycleit.BicycleModel'),
        ),
        migrations.AddField(
            model_name='bicycleconfiguration',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cycleit.User'),
        ),
        migrations.AddField(
            model_name='bicycleconfiguration',
            name='wheel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycleit.Wheel'),
        ),
    ]
