# Generated by Django 2.2.1 on 2019-05-11 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycleit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breaks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GroupSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BicycleConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breaks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycleit.Breaks')),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycleit.Frame')),
                ('group_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycleit.GroupSet')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycleit.BicycleModel')),
                ('wheel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycleit.Wheel')),
            ],
        ),
    ]
