# Generated by Django 2.2.1 on 2019-05-12 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycleit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForkName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HandlebarName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='GroupSet',
            new_name='ChainName',
        ),
        migrations.RemoveField(
            model_name='bicycleconfiguration',
            name='group_set',
        ),
        migrations.AddField(
            model_name='bicycleconfiguration',
            name='chain_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cycleit.ChainName'),
        ),
        migrations.AddField(
            model_name='bicycleconfiguration',
            name='fork_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cycleit.ForkName'),
        ),
        migrations.AddField(
            model_name='bicycleconfiguration',
            name='handlebar_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cycleit.HandlebarName'),
        ),
    ]
