# Generated by Django 2.2.1 on 2019-05-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycleit', '0003_auto_20190511_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='asd', max_length=200),
            preserve_default=False,
        ),
    ]
